site_name: memo blog

## Basic Configuration
theme:
  name: material
  #logo: assets/logo.png
  #favicon: images/favicon.ico

  #plugins:
        #  - search
        #- open-in-new-tab

extra:
  homepage: https://memo.ko-hei.net
